version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes: 
      - /home/fran/bd/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=helpdeskdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
